### ISSUE TITLE
issue with some PDFs

### ISSUE THREAD

**Issue by revolunet** [revolunet/pdf-factory#2]
issue with some PDF files when trying to fill fields.

in that case we should fallback to the "empty" PDF

Also the error message is misleading

``` sh
INFO     New Job!
Unhandled Java Exception:
java.lang.NullPointerException
   at com.lowagie.text.pdf.AcroFields.setGenerateAppearances(pdftk)
ERROR    Can't make request to service!
Traceback (most recent call last):
  File "supervisor.py", line 70, in <module>
    pdfFactory.process(json)
  File "/usr/lib/python2.6/site-packages/pdfFactory.py", line 237, in process
    clean_failure(tmp_dir, callback_url)
  File "/usr/lib/python2.6/site-packages/pdfFactory.py", line 67, in clean_failure
    sys.exit()
SystemExit
```

**Comment by jaganreddy** [comment]
I am getting same exception. Do you find any solution?

**Comment by revolunet** [comment]
the solution is to export the PDF with a lower PDF version (1.4) and make sur the PDF is not "protected"

**Comment by jaganreddy** [comment]
Thank you for quick reply. 
In my case user uploads the pdf file, filling the file in the application dynamically using pdftk command.

**Comment by revolunet** [comment]
BTW this issue is related to pdftk, not this project. maybe check with this fork : https://github.com/robinhouston/pdftk
